import time
from collections import defaultdict, deque
from typing import Annotated, Literal

from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from app import repository as repo
from app.agent import BOOKABLE, ChatSession, run_turn
from app.tools import doctor_card, slot_card
from app.config import get_settings
from app.db import get_session
from app.llm import LLM, OpenAICompatLLM
from app.triage import TriageResult

router = APIRouter(prefix="/api/v1", tags=["chat"])

SESSION_TTL_S = 30 * 60
MAX_SESSIONS = 1000
_sessions: dict[str, tuple[float, ChatSession]] = {}   # in memory only, expires after 30 min
_hits: dict[str, deque] = defaultdict(deque)


def get_llm() -> LLM:
    return OpenAICompatLLM()


def rate_limit(request: Request) -> None:
    """Simple sliding window per client IP. Production: per-user limits in a shared store (Redis)."""
    ip = request.client.host if request.client else "unknown"
    now, q = time.monotonic(), _hits[ip]
    while q and now - q[0] > 60:
        q.popleft()
    if len(q) >= get_settings().rate_limit_per_minute:
        raise HTTPException(status_code=429, detail="Too many messages. Please wait a minute.")
    q.append(now)


def _get_or_create(session_id: str | None) -> ChatSession:
    now = time.monotonic()
    for sid in [k for k, (t, _) in _sessions.items() if now - t > SESSION_TTL_S]:
        del _sessions[sid]
    if session_id and session_id in _sessions:
        s = _sessions[session_id][1]
    else:
        if len(_sessions) >= MAX_SESSIONS:
            raise HTTPException(status_code=503, detail="Service busy. Please try again shortly.")
        s = ChatSession()
    _sessions[s.id] = (now, s)
    return s


class ChatRequest(BaseModel):
    session_id: str | None = Field(default=None, pattern=r"^[a-f0-9]{32}$")
    message: str = Field(min_length=1, max_length=1000)
    language: Literal["en", "ar"] | None = None


class ChatResponse(BaseModel):
    session_id: str
    reply: str
    language: str
    triage: TriageResult | None
    providers: list[dict]        # DB rows only: the UI renders these, never the model's text
    hospitals: list[dict]
    slots: list[dict]            # open times from the DB; the patient confirms one via POST /bookings
    trace: list[dict]            # what happened this turn (facts → rule → tools); no patient text
    disclaimer: str = "Prototype with mock data. Not medical advice; this assistant does not diagnose."


@router.post("/chat", response_model=ChatResponse, dependencies=[Depends(rate_limit)])
def chat(req: ChatRequest, db: Annotated[Session, Depends(get_session)], llm: Annotated[LLM, Depends(get_llm)]):
    s = _get_or_create(req.session_id)
    r = run_turn(db, llm, s, req.message.strip(), req.language)
    return ChatResponse(session_id=s.id, reply=r.reply, language=r.language, triage=r.triage,
                        providers=r.providers, hospitals=r.hospitals, slots=r.slots, trace=r.trace)


class BookingRequest(BaseModel):
    session_id: str = Field(pattern=r"^[a-f0-9]{32}$")
    slot_id: int = Field(gt=0)


class BookingResponse(BaseModel):
    ticket_number: str           # generated by the database
    reply: str
    doctor: dict
    slot: dict


BOOKED_TEXT = {
    "en": "Your appointment is booked. Your ticket number is {ticket}. Please show it at {hospital} on {time}.",
    "ar": "تم حجز موعدك. رقم التذكرة: {ticket}. يُرجى إبرازه في {hospital} بتاريخ {time}.",
}


@router.post("/bookings", response_model=BookingResponse, dependencies=[Depends(rate_limit)])
def confirm_booking(req: BookingRequest, db: Annotated[Session, Depends(get_session)]):
    """Called by the patient's Confirm tap, never by the model. Every check is code:
    the session exists, its care path is bookable, and the slot is one WE offered in this
    conversation (so it belongs to a doctor who came from the database)."""
    entry = _sessions.get(req.session_id)
    if not entry:
        raise HTTPException(status_code=404, detail="Conversation not found or expired.")
    s = entry[1]
    if s.emergency_locked or s.care_path not in BOOKABLE:
        raise HTTPException(status_code=409, detail="Booking is not available for this conversation.")
    if req.slot_id not in s.offered_slot_ids:
        raise HTTPException(status_code=409, detail="This time was not offered in this conversation.")
    try:
        with db.begin():
            booking = repo.book_slot(db, req.slot_id)
            doctor = repo.get_doctor(db, booking.doctor_id)
            slot, ticket = slot_card(booking.slot, doctor), booking.ticket_number
            card = doctor_card(doctor)
    except repo.SlotUnavailable:
        raise HTTPException(status_code=409, detail="Sorry, this time was just taken. Please choose another.")
    lang = "ar" if s.history and any("\u0600" <= c <= "\u06ff" for c in s.history[-1]["content"]) else "en"
    hospital = card["hospital_name_ar"] if lang == "ar" else card["hospital_name"]
    reply = BOOKED_TEXT[lang].format(ticket=ticket, hospital=hospital, time=slot["local_time"])
    s.history.append({"role": "assistant", "content": reply})
    return BookingResponse(ticket_number=ticket, reply=reply, doctor=card, slot=slot)
